language: php

php:
 - 5.3
 - 5.4
 - 5.5

services:
 - memcached

before_script:
 - wget -nc http://getcomposer.org/composer.phar && php composer.phar install --prefer-source
 - mysql -e 'create database myapp_test;'

script: phpunit --bootstrap ./tests/bootstrap.php --coverage-text tests
