language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6

services:
 - memcached
 - redis-server

before_script:
 - ./tests/travis/memcache-setup.sh
 - ./tests/travis/memcached-setup.sh
 - ./tests/travis/composer-setup.sh
 - ./tests/travis/mysql-setup.sh

script: phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
