language: php

php:
 - 5.3
 - 5.4
 - 5.5

services:
 - memcached

before_script:
 - ./tests/travis/composer-setup.sh
 - ./tests/travis/mysql-setup.sh
 - ./tests/travis/memcache-setup.sh

script: phpunit --bootstrap ./tests/bootstrap.php --coverage-text --colors tests
